#!/usr/bin/env bash
#configuring nginx server to redirect to another page
sudo apt-get -y update
sudo apt-get install -y nginx

sed -i '/^\s*server_name \_\;$/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
