#!/usr/bin/env bash
#print "bad luck " at 4 "good luck" at 8 and "Best school " rest of iteration
i=0
while ((i < 10))
do
	if ((i == 3))
	then
		echo "bad luck"
	elif ((i == 7))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
