#!/usr/bin/env bash
#checking whether a file exit, not empty and is a regular file
file="school"
if [ -e "$file" ]
then
	echo "school file exist"
	if [ -s "$file" ]
	then
	    echo "shool is not empty file"
        else
	    echo "school is empty"
	fi
	if [ -f "$file" ]
        then
            echo "school is a regular file"  
        fi                                
else
	echo "school file does not exist"
fi
